wandb_version: 1

_n_gpu:
  desc: null
  value: 2
_name_or_path:
  desc: null
  value: VietAI/vit5-base
_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: huggingface
    huggingface_version: 4.21.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: train/global_step
      6:
      - 3
    python_version: 3.8.13
    start_time: 1665040576.50161
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 7
      - 13
      - 23
      4: 3.8.13
      5: 0.13.0
      6: 4.21.0.dev0
      8:
      - 2
      - 5
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - T5ForConditionalGeneration
auto_find_batch_size:
  desc: null
  value: false
bad_words_ids:
  desc: null
  value: null
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
bos_token_id:
  desc: null
  value: null
chunk_size_feed_forward:
  desc: null
  value: 0
cross_attention_hidden_size:
  desc: null
  value: null
d_ff:
  desc: null
  value: 3072
d_kv:
  desc: null
  value: 64
d_model:
  desc: null
  value: 768
data_seed:
  desc: null
  value: None
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_bucket_cap_mb:
  desc: null
  value: None
ddp_find_unused_parameters:
  desc: null
  value: None
debug:
  desc: null
  value: '[]'
decoder_start_token_id:
  desc: null
  value: 0
deepspeed:
  desc: null
  value: None
dense_act_fn:
  desc: null
  value: relu
disable_tqdm:
  desc: null
  value: false
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: true
dropout_rate:
  desc: null
  value: 0.1
early_stopping:
  desc: null
  value: false
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: None
eval_batch_size:
  desc: null
  value: 32
eval_delay:
  desc: null
  value: 0
eval_steps:
  desc: null
  value: None
evaluation_strategy:
  desc: null
  value: 'no'
exponential_decay_length_penalty:
  desc: null
  value: null
feed_forward_proj:
  desc: null
  value: relu
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
fsdp:
  desc: null
  value: '[]'
fsdp_min_num_params:
  desc: null
  value: 0
full_determinism:
  desc: null
  value: false
generation_max_length:
  desc: null
  value: None
generation_num_beams:
  desc: null
  value: None
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
greater_is_better:
  desc: null
  value: None
group_by_length:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
hub_model_id:
  desc: null
  value: None
hub_private_repo:
  desc: null
  value: false
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
ignore_data_skip:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
initializer_factor:
  desc: null
  value: 1.0
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: true
is_gated_act:
  desc: null
  value: false
jit_mode_eval:
  desc: null
  value: false
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
label_names:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
layer_norm_epsilon:
  desc: null
  value: 1.0e-06
learning_rate:
  desc: null
  value: 5.0e-05
length_column_name:
  desc: null
  value: length
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
log_level:
  desc: null
  value: -1
log_level_replica:
  desc: null
  value: -1
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ../tmp/tst-summarization/runs/Oct06_14-15-47_TungHT18
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 500
logging_strategy:
  desc: null
  value: steps
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: None
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: t5
mp_parameters:
  desc: null
  value: ''
n_positions:
  desc: null
  value: 512
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_decoder_layers:
  desc: null
  value: 12
num_heads:
  desc: null
  value: 12
num_layers:
  desc: null
  value: 12
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 3.0
optim:
  desc: null
  value: adamw_hf
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: ../tmp/tst-summarization
output_hidden_states:
  desc: null
  value: false
output_past:
  desc: null
  value: true
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: true
pad_token_id:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 16
per_device_train_batch_size:
  desc: null
  value: 16
per_gpu_eval_batch_size:
  desc: null
  value: None
per_gpu_train_batch_size:
  desc: null
  value: None
predict_with_generate:
  desc: null
  value: true
prediction_loss_only:
  desc: null
  value: false
prefix:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: None
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
ray_scope:
  desc: null
  value: last
relative_attention_max_distance:
  desc: null
  value: 128
relative_attention_num_buckets:
  desc: null
  value: 32
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value: '[''tensorboard'', ''wandb'']'
resume_from_checkpoint:
  desc: null
  value: None
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
run_name:
  desc: null
  value: ../tmp/tst-summarization
save_on_each_node:
  desc: null
  value: false
save_steps:
  desc: null
  value: 500
save_strategy:
  desc: null
  value: steps
save_total_limit:
  desc: null
  value: None
seed:
  desc: null
  value: 42
sep_token_id:
  desc: null
  value: null
sharded_ddp:
  desc: null
  value: '[]'
skip_memory_metrics:
  desc: null
  value: true
sortish_sampler:
  desc: null
  value: false
task_specific_params:
  desc: null
  value: null
temperature:
  desc: null
  value: 1.0
tf32:
  desc: null
  value: None
tf_legacy_loss:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: true
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torch_dtype:
  desc: null
  value: float32
torchdynamo:
  desc: null
  value: None
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 32
transformers_version:
  desc: null
  value: 4.21.0.dev0
typical_p:
  desc: null
  value: 1.0
use_bfloat16:
  desc: null
  value: false
use_cache:
  desc: null
  value: true
use_ipex:
  desc: null
  value: false
use_legacy_prediction_loop:
  desc: null
  value: false
vocab_size:
  desc: null
  value: 36096
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
xpu_backend:
  desc: null
  value: None
